apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: trafficap
spec:
  selector:
    matchLabels:
      name: trafficap
  template:
    metadata:
      labels:
        name: trafficap
    spec:
      hostNetwork: true
      containers:
      - name: tcpdumper
        image: docker.io/dockersec/tcpdump
        imagePullPolicy: Always
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: vhost
            mountPath: /host
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /
          name: vhost