apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  labels:
    app: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: 561341012850.dkr.ecr.us-east-1.amazonaws.com/team23-auth-api:latest
        ports:
        - containerPort: 8081