apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  labels:
    app: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: 561341012850.dkr.ecr.us-east-1.amazonaws.com/team23-users-api:latest
        ports:
        - containerPort: 8083